- hosts: myweb, proxyserver
  vars_files:
  - variable.yml
  tasks:
  - name: "Disabling SELINUX !!!"
    selinux:
      policy: targeted
      state: permissive
  - name: "Creating directory for ISO device"
    file:
      path: "/{{ dir_name}}"
      state: directory
  - name: "mounting the iso drive on the folder"
    mount:
      path: "/{{ dir_name }}"
      src: "/dev/sr0"
      fstype: iso9660
      state: mounted
  - name: "Configuring yum with AppStream"
    yum_repository:
            name: "AppStream"
            description: "A repo for AppStream Setup"
            baseurl: "file:///dvd/AppStream"
            gpgcheck: no
  - name: "Configuring yum with BaseOS"
    yum_repository:
            name: "BaseOS"
            description: "A repo for BaseOS Setup"
            baseurl: "file:///dvd/BaseOS"
            gpgcheck: no
- hosts: myweb
  vars_files:
  - variable.yml
  tasks:
  - name: "installing Httpd package"
    package:
            name: "httpd"
            state: present
  - name: "installing PHP package"
    package:
            name: "php"
            state: present
  - name: "Copying web server code!!!!"
    copy:
            src: "index.php"
            dest: "/root/var/www/html/"
            mode: '0644'
  - name: "Firewall service disabling"
    service:
            name: 'firewalld'
            state: stopped
  - name: "Starting the service"
    service:
            name: "httpd"
            state: restarted
            enabled: yes

- hosts: proxyserver
  vars_files:
  - variable.yml
  vars:
       ip_list: "{{ groups['myweb']  }}"
       count: 1
  tasks:
  - debug:
            msg: "{{ groups['myweb']  }}"
  - name: "Installing the proxy server"
    package:
            name: 'haproxy'
            state: present
  - name: 'Adding conf file'
    template:
            src: 'haproxy.cfg.j2'
            dest: '/etc/haproxy/haproxy.cfg'
    notify:
    - 'starting the service'
  - name: 'Disabling the firewall service'
    service:
            name: 'firewalld'
            state: stopped
  handlers:
    - name: "starting the service"
      service:
            name: 'haproxy'
            state: restarted
            enabled: yes
